Import relevant libraries

In [174]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

Load datasets

In [175]:
eco = pd.read_csv('economy.csv')
business = pd.read_csv('business.csv')

eco.head(), business.head()

(         date   airline ch_code  num_code dep_time   from time_taken  \
 0  11-02-2022  SpiceJet      SG      8709    18:55  Delhi    02h 10m
 1  11-02-2022  SpiceJet      SG      8157    06:20  Delhi    02h 20m
 2  11-02-2022   AirAsia      I5       764    04:25  Delhi    02h 10m
 3  11-02-2022   Vistara      UK       995    10:20  Delhi    02h 15m
 4  11-02-2022   Vistara      UK       963    08:50  Delhi    02h 20m

         stop arr_time      to  price
 0  non-stop     21:05  Mumbai  5,953
 1  non-stop     08:40  Mumbai  5,953
 2  non-stop     06:35  Mumbai  5,956
 3  non-stop     12:35  Mumbai  5,955
 4  non-stop     11:10  Mumbai  5,955  ,
          date    airline ch_code  num_code dep_time   from time_taken  \
 0  11-02-2022  Air India      AI       868    18:00  Delhi    02h 00m
 1  11-02-2022  Air India      AI       624    19:00  Delhi    02h 15m
 2  11-02-2022  Air India      AI       531    20:00  Delhi    24h 45m
 3  11-02-2022  Air India      AI       839    21:25  Delhi    26h 30m
 4  11-02-2022  Air India      AI       544    17:15  Delhi    06h 40m

                                                 stop arr_time      to   price
 0                                          non-stop     20:00  Mumbai  25,612
 1                                          non-stop     21:15  Mumbai  25,612
 2  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    20:45  Mumbai  42,220
 3  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    23:55  Mumbai  44,450
 4  1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...    23:55  Mumbai  46,690  )

In [176]:
#adding new feature for category
eco['category'] = 'economy'
eco.shape

(206774, 12)

In [177]:
business['category'] = 'business'
business.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,category
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",business
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",business
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",business
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",business
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",business

In [178]:
#drop head from business and merge both dataframes
df = pd.concat([eco, business], ignore_index=True)
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,category
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",economy
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",economy
2,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",economy
3,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",economy
4,11-02-2022,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",economy

Explore Dataset

In [179]:
df.isnull().sum()

date          0
airline       0
ch_code       0
num_code      0
dep_time      0
from          0
time_taken    0
stop          0
arr_time      0
to            0
price         0
category      0
dtype: int64

In [180]:
#explore dates
df['date'].value_counts()

#dates ranges from feb 2022 till mar 2022

#we can split and convert in month and day
df['day'] = df['date'].str.split('-').str[0]
df['month'] = df['date'].str.split('-').str[1]

df.drop('date', axis=1, inplace=True)

df.head()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,category,day,month
0,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",economy,11,02
1,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",economy,11,02
2,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",economy,11,02
3,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",economy,11,02
4,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",economy,11,02

In [181]:
#check unique months
df['day'].unique()

array(['11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
       '22', '23', '24', '25', '26', '27', '28', '01', '02', '03', '04',
       '05', '06', '07', '08', '09', '10', '29', '30', '31'], dtype=object)

In [182]:
#num_code we can drop
df.drop('num_code', axis=1, inplace=True)

In [183]:
#lets explore airline
df['airline'].value_counts()

#no fe needed we can directly do lable encoding on airline

airline
Vistara      127859
Air India     80894
Indigo        43120
GO FIRST      23177
AirAsia       16098
SpiceJet       9011
StarAir          61
Trujet           41
Name: count, dtype: int64

In [184]:
#lets explore dep_time
df['dep_time'].value_counts()

#we can solit in hour and min for departure

df['dep_hr'] = df['dep_time'].str.split(':').str[0]
df['dep_min'] = df['dep_time'].str.split(':').str[1]

#now we can drop dep_time
df.drop('dep_time', axis=1, inplace=True)

In [185]:
df.head()

,airline,ch_code,from,time_taken,stop,arr_time,to,price,category,day,month,dep_hr,dep_min
0,SpiceJet,SG,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",economy,11,02,18,55
1,SpiceJet,SG,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",economy,11,02,06,20
2,AirAsia,I5,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",economy,11,02,04,25
3,Vistara,UK,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",economy,11,02,10,20
4,Vistara,UK,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",economy,11,02,08,50

In [186]:
Counter(df['time_taken'])

Counter({'02h 10m': 4242,
         '02h 15m': 4036,
         '02h 45m': 2879,
         '02h 05m': 2755,
         '02h 50m': 2323,
         '12h 00m': 2224,
         '02h 20m': 2053,
         '07h 35m': 2045,
         '08h 00m': 2040,
         '11h 10m': 1999,
         '06h 40m': 1913,
         '09h 30m': 1864,
         '07h 20m': 1830,
         '09h 20m': 1821,
         '12h 05m': 1800,
         '10h 10m': 1782,
         '12h 25m': 1768,
         '11h 25m': 1762,
         '05h 35m': 1753,
         '10h 30m': 1750,
         '08h 15m': 1748,
         '08h 05m': 1728,
         '13h 05m': 1701,
         '11h 15m': 1698,
         '12h 15m': 1697,
         '13h 10m': 1689,
         '06h 20m': 1679,
         '06h 10m': 1666,
         '10h 15m': 1659,
         '10h 00m': 1659,
         '08h 50m': 1628,
         '13h 00m': 1622,
         '05h 40m': 1605,
         '06h 35m': 1600,
         '07h 10m': 1599,
         '08h 45m': 1589,
         '08h 35m': 1587,
         '10h 50m': 1582,
         '13h 55m': 1582,
         '16h 00m': 1579,
         '07h 05m': 1564,
         '02h 40m': 1564,
         '14h 15m': 1557,
         '12h 45m': 1547,
         '07h 00m': 1529,
         '14h 10m': 1517,
         '09h 10m': 1517,
         '14h 55m': 1512,
         '15h 05m': 1502,
         '07h 40m': 1497,
         '15h 10m': 1487,
         '06h 00m': 1469,
         '09h 15m': 1466,
         '06h 45m': 1464,
         '09h 40m': 1458,
         '11h 30m': 1456,
         '02h 55m': 1430,
         '06h 05m': 1425,
         '09h 35m': 1422,
         '02h 30m': 1418,
         '14h 00m': 1408,
         '15h 15m': 1404,
         '08h 20m': 1399,
         '08h 25m': 1392,
         '09h 50m': 1384,
         '14h 05m': 1380,
         '11h 20m': 1371,
         '07h 25m': 1370,
         '06h 15m': 1369,
         '06h 25m': 1368,
         '09h 45m': 1360,
         '07h 30m': 1358,
         '12h 20m': 1357,
         '11h 40m': 1357,
         '11h 45m': 1354,
         '16h 10m': 1354,
         '12h 35m': 1347,
         '10h 05m': 1335,
         '05h 25m': 1327,
         '05h 00m': 1317,
         '06h 30m': 1311,
         '05h 30m': 1302,
         '05h 45m': 1298,
         '10h 55m': 1298,
         '05h 50m': 1296,
         '13h 15m': 1293,
         '11h 00m': 1288,
         '13h 50m': 1286,
         '12h 30m': 1280,
         '06h 55m': 1278,
         '12h 10m': 1271,
         '14h 25m': 1266,
         '10h 45m': 1265,
         '15h 00m': 1260,
         '13h 35m': 1255,
         '02h 25m': 1252,
         '11h 55m': 1235,
         '15h 55m': 1233,
         '05h 55m': 1230,
         '12h 40m': 1201,
         '15h 25m': 1193,
         '08h 40m': 1189,
         '01h 50m': 1187,
         '05h 05m': 1179,
         '09h 05m': 1178,
         '13h 25m': 1171,
         '02h 35m': 1166,
         '09h 55m': 1165,
         '06h 50m': 1163,
         '14h 45m': 1148,
         '14h 30m': 1122,
         '04h 55m': 1122,
         '05h 20m': 1121,
         '08h 55m': 1115,
         '08h 10m': 1114,
         '13h 30m': 1111,
         '07h 15m': 1105,
         '16h 55m': 1103,
         '01h 45m': 1102,
         '08h 30m': 1099,
         '11h 35m': 1097,
         '05h 15m': 1093,
         '11h 05m': 1085,
         '10h 25m': 1079,
         '07h 45m': 1076,
         '01h 55m': 1076,
         '07h 50m': 1065,
         '07h 55m': 1063,
         '12h 50m': 1062,
         '13h 45m': 1059,
         '14h 35m': 1054,
         '22h 15m': 1049,
         '17h 25m': 1043,
         '16h 05m': 1037,
         '11h 50m': 1028,
         '10h 20m': 1026,
         '15h 45m': 1023,
         '05h 10m': 1012,
         '15h 50m': 1010,
         '10h 40m': 993,
         '12h 55m': 991,
         '16h 30m': 988,
         '22h 20m': 971,
         '01h 10m': 960,
         '24h 20m': 956,
         '13h 20m': 942,
         '14h 50m': 934,
         '02h 00m': 933,
         '13h 40m': 933,
         '10h 35m': 931,
         '09h 25m': 925,
         '16h 25m': 924,
         '15h 40m': 894,
         '09h 00m': 893,
         '04h 45m': 886,
         '15h 30m': 884,
         '01h 20m': 853,
         '15h 35m': 840,
         '17h 30m': 816,
         '14h 40m': 814,
         '23h 20m': 814,
         '16h 20m': 813,
         '17h 10m': 805,
         '01h 15m': 804,
         '01h 30m': 800,
         '17h 55m': 797,
         '26h 30m': 784,
         '16h 40m': 782,
         '25h 55m': 774,
         '17h 20m': 750,
         '25h 05m': 736,
         '01h 40m': 729,
         '24h 00m': 724,
         '23h 50m': 721,
         '21h 30m': 702,
         '25h 30m': 694,
         '24h 55m': 685,
         '25h 00m': 685,
         '19h 55m': 679,
         '26h 10m': 673,
         '04h 50m': 669,
         '23h 15m': 667,
         '17h 00m': 662,
         '22h 25m': 657,
         '01h 35m': 655,
         '25h 40m': 653,
         '22h 30m': 646,
         '24h 10m': 645,
         '23h 05m': 643,
         '24h 05m': 635,
         '26h 05m': 631,
         '22h 10m': 626,
         '16h 50m': 623,
         '21h 40m': 622,
         '14h 20m': 614,
         '16h 15m': 612,
         '25h 10m': 609,
         '26h 45m': 606,
         '23h 00m': 598,
         '26h 25m': 590,
         '04h 30m': 585,
         '04h 40m': 578,
         '01h 05m': 573,
         '17h 05m': 572,
         '20h 25m': 570,
         '21h 50m': 569,
         '23h 55m': 568,
         '20h 35m': 565,
         '26h 35m': 560,
         '25h 45m': 553,
         '17h 50m': 548,
         '20h 10m': 548,
         '24h 25m': 534,
         '25h 20m': 532,
         '19h 20m': 524,
         '22h 55m': 524,
         '21h 15m': 516,
         '25h 25m': 515,
         '16h 35m': 512,
         '24h 50m': 510,
         '20h 20m': 510,
         '04h 35m': 508,
         '21h 10m': 506,
         '26h 20m': 506,
         '19h 30m': 503,
         '26h 40m': 499,
         '25h 15m': 499,
         '27h 30m': 499,
         '23h 10m': 498,
         '23h 35m': 498,
         '22h 50m': 497,
         '25h 50m': 491,
         '19h 15m': 488,
         '04h 15m': 484,
         '24h 15m': 478,
         '16h 45m': 461,
         '25h 35m': 459,
         '19h 25m': 457,
         '21h 05m': 456,
         '04h 10m': 456,
         '24h 40m': 452,
         '17h 40m': 445,
         '22h 40m': 444,
         '23h 30m': 443,
         '19h 00m': 443,
         '27h 20m': 437,
         '18h 20m': 432,
         '17h 35m': 432,
         '24h 30m': 431,
         '26h 15m': 428,
         '23h 40m': 427,
         '18h 55m': 423,
         '27h 10m': 421,
         '22h 05m': 419,
         '26h 00m': 418,
         '18h 15m': 414,
         '26h 55m': 413,
         '18h 10m': 398,
         '04h 20m': 397,
         '01h 00m': 397,
         '28h 00m': 395,
         '22h 45m': 389,
         '24h 35m': 387,
         '04h 25m': 386,
         '21h 00m': 386,
         '04h 05m': 385,
         '18h 40m': 380,
         '17h 15m': 372,
         '03h 55m': 361,
         '21h 35m': 360,
         '03h 45m': 359,
         '27h 35m': 352,
         '19h 45m': 337,
         '19h 10m': 334,
         '20h 30m': 333,
         '24h 45m': 327,
         '18h 35m': 326,
         '18h 30m': 325,
         '20h 40m': 320,
         '20h 15m': 318,
         '22h 00m': 317,
         '15h 20m': 311,
         '20h 05m': 309,
         '18h 05m': 309,
         '27h 55m': 299,
         '03h 00m': 297,
         '17h 45m': 290,
         '20h 50m': 289,
         '28h 20m': 285,
         '19h 05m': 276,
         '19h 50m': 272,
         '26h 50m': 269,
         '18h 45m': 268,
         '18h 00m': 265,
         '23h 45m': 255,
         '22h 35m': 254,
         '20h 55m': 253,
         '21h 20m': 248,
         '27h 05m': 248,
         '21h 45m': 241,
         '21h 25m': 241,
         '23h 25m': 238,
         '01h 25m': 237,
         '19h 40m': 224,
         '03h 40m': 223,
         '03h 50m': 221,
         '27h 15m': 218,
         '18h 50m': 213,
         '28h 15m': 200,
         '28h 25m': 186,
         '18h 25m': 186,
         '27h 00m': 185,
         '20h 45m': 179,
         '27h 45m': 175,
         '20h 00m': 172,
         '03h 05m': 167,
         '28h 35m': 165,
         '28h 05m': 160,
         '19h 35m': 156,
         '21h 55m': 156,
         '29h 10m': 151,
         '27h 50m': 145,
         '03h 30m': 144,
         '28h 10m': 131,
         '31h 10m': 128,
         '28h 30m': 126,
         '30h 35m': 125,
         '29h 30m': 120,
         '04h 00m': 115,
         '29h 40m': 114,
         '31h 05m': 111,
         '30h 15m': 106,
         '29h 50m': 101,
         '30h 00m': 99,
         '03h 35m': 96,
         '30h 05m': 94,
         '03h 25m': 94,
         '27h 25m': 93,
         '28h 55m': 78,
         '00h 55m': 78,
         '03h 10m': 77,
         '33h 40m': 76,
         '31h 15m': 73,
         '37h 00m': 69,
         '27h 40m': 65,
         '33h 50m': 61,
         '28h 40m': 60,
         '33h 25m': 57,
         '29h 00m': 53,
         '00h 50m': 52,
         '29h 25m': 50,
         '28h 50m': 49,
         '32h 10m': 49,
         '31h 35m': 47,
         '03h 15m': 45,
         '31h 55m': 44,
         '33h 45m': 42,
         '30h 20m': 42,
         '35h 25m': 42,
         '30h 30m': 41,
         '35h 05m': 39,
         '34h 20m': 37,
         '31h 30m': 35,
         '31h 20m': 34,
         '29h 20m': 33,
         '33h 55m': 33,
         '32h 00m': 32,
         '29h 05m': 32,
         '29h 35m': 31,
         '34h 35m': 29,
         '32h 05m': 28,
         '30h 45m': 28,
         '33h 30m': 27,
         '03h 20m': 27,
         '33h 35m': 26,
         '29h 45m': 25,
         '2h 25m': 25,
         '35h 35m': 25,
         '30h 40m': 24,
         '40h 25m': 24,
         '28h 45m': 22,
         '30h 10m': 22,
         '35h 45m': 22,
         '33h 00m': 22,
         '38h 35m': 20,
         '34h 05m': 19,
         '34h 50m': 18,
         '31h 00m': 18,
         '36h 50m': 17,
         '32h 45m': 17,
         '34h 10m': 16,
         '34h 00m': 16,
         '31h 50m': 15,
         '29h 15m': 15,
         '32h 25m': 15,
         '06h 59m': 15,
         '13h 24m': 15,
         '34h 15m': 14,
         '37h 35m': 14,
         '36h 05m': 12,
         '34h 55m': 12,
         '33h 10m': 11,
         '33h 20m': 11,
         '29h 55m': 11,
         '37h 55m': 11,
         '35h 15m': 10,
         '32h 30m': 10,
         '31h 45m': 10,
         '36h 00m': 10,
         '39h 55m': 10,
         '31h 40m': 9,
         '34h 30m': 9,
         '35h 10m': 9,
         '33h 15m': 9,
         '32h 40m': 8,
         '5h 30m': 8,
         '7h 20m': 7,
         '31h 25m': 7,
         '33h 05m': 7,
         '30h 25m': 7,
         '32h 20m': 7,
         '30h 50m': 6,
         '36h 35m': 6,
         '32h 50m': 6,
         '32h 35m': 6,
         '36h 55m': 5,
         '06h 04m': 5,
         '35h 50m': 5,
         '36h 25m': 5,
         '32h 55m': 5,
         '39h 40m': 4,
         '36h 10m': 4,
         '37h 20m': 4,
         '30h 55m': 4,
         '34h 25m': 4,
         '35h 20m': 4,
         '37h 05m': 3,
         '37h 50m': 3,
         '37h 40m': 3,
         '37h 45m': 3,
         '35h 30m': 3,
         '39h 00m': 3,
         '34h 45m': 3,
         '36h 30m': 3,
         '40h 40m': 3,
         '40h 30m': 3,
         '39h 05m': 3,
         '35h 55m': 3,
         '32h 15m': 3,
         '45h 50m': 3,
         '37h 25m': 2,
         '40h 00m': 2,
         '37h 15m': 2,
         '39h 45m': 2,
         '1.03h m': 2,
         '38h 50m': 2,
         '41h 50m': 2,
         '47h 45m': 2,
         '34h 40m': 2,
         '39h 50m': 2,
         '37h 30m': 2,
         '40h 55m': 2,
         '38h 20m': 2,
         '36h 45m': 2,
         '49h 50m': 2,
         '39h 25m': 2,
         '41h 35m': 1,
         '37h 10m': 1,
         '1.02h m': 1,
         '36h 15m': 1,
         '40h 45m': 1,
         '38h 30m': 1,
         '1.01h m': 1,
         '38h 45m': 1,
         '2h 50m': 1,
         '42h 00m': 1,
         '38h 40m': 1,
         '39h 15m': 1,
         '41h 05m': 1,
         '35h 40m': 1,
         '47h 05m': 1,
         '44h 30m': 1,
         '41h 30m': 1})

In [187]:
#let's treat time taken 
df['time_taken'].sort_values()
#we can again split in hr and min
df['duration_hr'] = df['time_taken'].str.split('h ').str[0]
df['duration_min'] = df['time_taken'].str.split(" ").str[1]
df['duration_min'] = df['duration_min'].str.split("m").str[0]

#no we can drop time taken
df.drop('time_taken', axis =1, inplace = True)

In [188]:
df.head()

,airline,ch_code,from,stop,arr_time,to,price,category,day,month,dep_hr,dep_min,duration_hr,duration_min
0,SpiceJet,SG,Delhi,non-stop,21:05,Mumbai,"5,953",economy,11,02,18,55,02,10
1,SpiceJet,SG,Delhi,non-stop,08:40,Mumbai,"5,953",economy,11,02,06,20,02,20
2,AirAsia,I5,Delhi,non-stop,06:35,Mumbai,"5,956",economy,11,02,04,25,02,10
3,Vistara,UK,Delhi,non-stop,12:35,Mumbai,"5,955",economy,11,02,10,20,02,15
4,Vistara,UK,Delhi,non-stop,11:10,Mumbai,"5,955",economy,11,02,08,50,02,20

In [189]:
df.isnull().sum()

airline         0
ch_code         0
from            0
stop            0
arr_time        0
to              0
price           0
category        0
day             0
month           0
dep_hr          0
dep_min         0
duration_hr     0
duration_min    0
dtype: int64

In [190]:
#also, we can calcualte total duration in minutes

#but first convert into intergers
df['duration_hr'] = (df['duration_hr'].astype(float)).astype(int)
df['duration_min'] = df['duration_min'].replace('', 0)
df['duration_min'] = df['duration_min'].astype(int)

df['total_duration'] = (df['duration_hr']*60) + df['duration_min']
df['total_duration']

0         130
1         140
2         130
3         135
4         140
         ...
300256    605
300257    625
300258    830
300259    600
300260    605
Name: total_duration, Length: 300261, dtype: int64

In [191]:
#we can drop arrivan time and departure time and duration can be used to derive this along with duration hr and min\
df.drop(['arr_time', 'duration_hr', 'duration_min'], axis = 1, inplace = True)

In [192]:
df.head()

,airline,ch_code,from,stop,to,price,category,day,month,dep_hr,dep_min,total_duration
0,SpiceJet,SG,Delhi,non-stop,Mumbai,"5,953",economy,11,02,18,55,130
1,SpiceJet,SG,Delhi,non-stop,Mumbai,"5,953",economy,11,02,06,20,140
2,AirAsia,I5,Delhi,non-stop,Mumbai,"5,956",economy,11,02,04,25,130
3,Vistara,UK,Delhi,non-stop,Mumbai,"5,955",economy,11,02,10,20,135
4,Vistara,UK,Delhi,non-stop,Mumbai,"5,955",economy,11,02,08,50,140

In [193]:
#lets look into ch_code
df['ch_code'].unique()

<StringArray>
['SG', 'I5', 'UK', 'G8', '6E', 'AI', '2T', 'S5']
Length: 8, dtype: str

In [194]:
#lets check stop feature
df['stop'].value_counts()

#let's get rid of \, n, \t first
business['stop'] = business['stop'].astype(str).str.strip()
df['stop'].value_counts()

stop
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t                      243603
non-stop                                                                         36044
2+-stop                                                                          13288
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXU\n\t\t\t\t\t\t\t\t\t\t\t\t                 1839
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IDR\n\t\t\t\t\t\t\t\t\t\t\t\t                 1398
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Patna\n\t\t\t\t\t\t\t\t\t\t\t\t                674
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Indore\n\t\t\t\t\t\t\t\t\t\t\t\t               381
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia PAT\n\t\t\t\t\t\t\t\t\t\t\t\t                  354
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia MYQ\n\t\t\t\t\t\t\t\t\t\t\t\t                  321
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Bhubaneswar\n\t\t\t\t\t\t\t\t\t\t\t\t          301
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia KLH\n\t\t\t\t\t\t\t\t\t\t\t\t                  284
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia JGB\n\t\t\t\t\t\t\t\t\t\t\t\t                  193
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia JRG\n\t\t\t\t\t\t\t\t\t\t\t\t                  175
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia STV\n\t\t\t\t\t\t\t\t\t\t\t\t                  169
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia BBI\n\t\t\t\t\t\t\t\t\t\t\t\t                  158
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Delhi\n\t\t\t\t\t\t\t\t\t\t\t\t                153
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Hyderabad\n\t\t\t\t\t\t\t\t\t\t\t\t            143
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXE\n\t\t\t\t\t\t\t\t\t\t\t\t                  120
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Ranchi\n\t\t\t\t\t\t\t\t\t\t\t\t               114
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Raipur\n\t\t\t\t\t\t\t\t\t\t\t\t               102
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Chennai\n\t\t\t\t\t\t\t\t\t\t\t\t               77
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Guwahati\n\t\t\t\t\t\t\t\t\t\t\t\t              55
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Mysore\n\t\t\t\t\t\t\t\t\t\t\t\t                45
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Mangalore\n\t\t\t\t\t\t\t\t\t\t\t\t             39
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Mumbai\n\t\t\t\t\t\t\t\t\t\t\t\t                31
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolkata\n\t\t\t\t\t\t\t\t\t\t\t\t               28
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia VTZ\n\t\t\t\t\t\t\t\t\t\t\t\t                   27
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Nagpur\n\t\t\t\t\t\t\t\t\t\t\t\t                25
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia RPR\n\t\t\t\t\t\t\t\t\t\t\t\t                   22
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NDC\n\t\t\t\t\t\t\t\t\t\t\t\t                   22
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GOP\n\t\t\t\t\t\t\t\t\t\t\t\t                   16
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Surat\n\t\t\t\t\t\t\t\t\t\t\t\t                 14
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Lucknow\n\t\t\t\t\t\t\t\t\t\t\t\t               13
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NAG\n\t\t\t\t\t\t\t\t\t\t\t\t                    9
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Vishakhapatnam\n\t\t\t\t\t\t\t\t\t\t\t\t         8
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolhapur\n\t\t\t\t\t\t\t\t\t\t\t\t               5
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXR\n\t\t\t\t\t\t\t\t\t\t\t\t                    4
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAY\n\t\t\t\t\t\t\t\t\t\t\t\t                    3
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAU\n\t\t\t\t\t\t\t\t\t\t\t\t                    3
1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia HYD\n\t\t\t\t\t\t\t\t\t\t\t\t                    1
Name: count, dtype: int64

In [195]:
#let's extract stops
df['total_stop'] = df['stop'].str.strip(' ').str[0]
df['total_stop'].value_counts()

#replace n with 0 and convert in int
df['total_stop'] = df['total_stop'].replace('n', 0)
df.isnull().sum()

airline           0
ch_code           0
from              0
stop              0
to                0
price             0
category          0
day               0
month             0
dep_hr            0
dep_min           0
total_duration    0
total_stop        0
dtype: int64

In [196]:
#lets drop stop
df.drop('stop', axis = 1, inplace = True)

In [197]:
#lets explore from and to
df['from'].value_counts(), df['to'].value_counts()

(from
 Delhi        61345
 Mumbai       60903
 Bangalore    52106
 Kolkata      46347
 Hyderabad    40860
 Chennai      38700
 Name: count, dtype: int64,
 to
 Mumbai       59109
 Delhi        57361
 Bangalore    51112
 Kolkata      49535
 Hyderabad    42776
 Chennai      40368
 Name: count, dtype: int64)

In [198]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300261 entries, 0 to 300260
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   airline         300261 non-null  str
 1   ch_code         300261 non-null  str
 2   from            300261 non-null  str
 3   to              300261 non-null  str
 4   price           300261 non-null  str
 5   category        300261 non-null  str
 6   day             300261 non-null  object
 7   month           300261 non-null  object
 8   dep_hr          300261 non-null  object
 9   dep_min         300261 non-null  object
 10  total_duration  300261 non-null  int64
 11  total_stop      300261 non-null  object
dtypes: int64(1), object(5), str(6)
memory usage: 27.5+ MB

In [200]:
#change datatypes of obj to int 
df[['day','month', 'dep_hr', 'dep_min', 'total_duration', 'total_stop']] = df[['day','month', 'dep_hr', 'dep_min', 'total_duration', 'total_stop']].astype(int)

In [218]:
#let's fix price
df['price'] = df['price'].replace(',','', regex= True)

df['price'] = df['price'].astype(int)

In [219]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300261 entries, 0 to 300260
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   airline         300261 non-null  str
 1   ch_code         300261 non-null  str
 2   from            300261 non-null  str
 3   to              300261 non-null  str
 4   price           300261 non-null  int64
 5   category        300261 non-null  str
 6   day             300261 non-null  int64
 7   month           300261 non-null  int64
 8   dep_hr          300261 non-null  int64
 9   dep_min         300261 non-null  int64
 10  total_duration  300261 non-null  int64
 11  total_stop      300261 non-null  int64
dtypes: int64(7), str(5)
memory usage: 27.5 MB

Data is now cleaned

In [223]:
#from str to obj
df[['airline', 'ch_code', 'from', 'to', 'category']] = df[['airline', 'ch_code', 'from', 'to', 'category']].astype(object)

Exploratory visualizations

In [225]:
df.head()

,airline,ch_code,from,to,price,category,day,month,dep_hr,dep_min,total_duration,total_stop
0,SpiceJet,SG,Delhi,Mumbai,5953,economy,11,2,18,55,130,0
1,SpiceJet,SG,Delhi,Mumbai,5953,economy,11,2,6,20,140,0
2,AirAsia,I5,Delhi,Mumbai,5956,economy,11,2,4,25,130,0
3,Vistara,UK,Delhi,Mumbai,5955,economy,11,2,10,20,135,0
4,Vistara,UK,Delhi,Mumbai,5955,economy,11,2,8,50,140,0

In [228]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300261 entries, 0 to 300260
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   airline         300261 non-null  object
 1   ch_code         300261 non-null  object
 2   from            300261 non-null  object
 3   to              300261 non-null  object
 4   price           300261 non-null  int64
 5   category        300261 non-null  object
 6   day             300261 non-null  int64
 7   month           300261 non-null  int64
 8   dep_hr          300261 non-null  int64
 9   dep_min         300261 non-null  int64
 10  total_duration  300261 non-null  int64
 11  total_stop      300261 non-null  int64
dtypes: int64(7), object(5)
memory usage: 27.5+ MB

In [ ]:
df.to_csv('flight_price_cleaned.csv')